project:
  type: website

website:
  title: "HuggingFace KREW"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ./blog/blog.qmd
        text: Blog
      - about.qmd
        
  google-analytics: "G-L42RQMBKSP"
  page-footer:
    center: "HuggingFace KREW"
        format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

